"""Content Agent — transforms YouTube videos into structured content.

Full pipeline: fetch transcript → classify → transform → save → log.

Usage:
    python3 content_agent.py <youtube_url> [--format summary|chapters|blog-post|thread|quotes]
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from echo_core import classify_task, log_routing

# Paths
CONTENT_DIR = Path("~/.echo-core/content").expanduser()
AGENT_LOG = Path("~/.echo-core/logs/agent-log.jsonl").expanduser()
TRANSCRIPT_SCRIPT = Path(
    "~/.echo-core/.hermes/skills/media/youtube-content/scripts/fetch_transcript.py"
).expanduser()

# If the skill path doesn't resolve from echo-core, use the home-relative path
if not TRANSCRIPT_SCRIPT.exists():
    TRANSCRIPT_SCRIPT = Path.home() / ".hermes/skills/media/youtube-content/scripts/fetch_transcript.py"


def fetch_transcript(url: str) -> str:
    """Fetch a YouTube transcript with timestamps. Returns timestamped text."""
    import subprocess
    result = subprocess.run(
        ["python3", str(TRANSCRIPT_SCRIPT), url, "--text-only", "--timestamps"],
        capture_output=True, text=True, timeout=60
    )
    if result.returncode != 0:
        raise RuntimeError(f"Transcript fetch failed: {result.stderr.strip()}")
    return result.stdout.strip()


def format_summary(transcript: str, title: str) -> str:
    """Format the transcript as a concise summary."""
    word_count = len(transcript.split())
    # Extract first line as a rough intro
    lines = transcript.strip().split("\n")
    first_timestamp = lines[0].split(" ", 1)[0] if lines else "0:00"
    last_line = lines[-1] if lines else ""
    last_timestamp = last_line.split(" ", 1)[0] if last_line else "0:00"

    return f"""# Summary: {title}

**Duration:** {first_timestamp} – {last_timestamp}
**Words:** {word_count}

## Key Points

Based on the transcript ({word_count} words across {len(lines)} segments):

- Video covers content from {first_timestamp} to {last_timestamp}
- {len(lines)} timestamped segments processed
- [Full transcript available below]

## Transcript

{transcript}

---
*Generated by echo-core-content-agent | {datetime.now(timezone.utc).isoformat()}*
"""


def format_chapters(transcript: str, title: str) -> str:
    """Extract chapter-like structure from the transcript."""
    lines = transcript.strip().split("\n")
    # Group into rough chapters by time blocks
    chapters = []
    current_chapter = None
    chapter_lines = []

    for line in lines:
        if not line.strip():
            continue
        ts = line.split(" ", 1)[0] if " " in line else "0:00"
        text = line[len(ts):].strip() if " " in line else line

        # New chapter every ~30 seconds or on major topic shifts
        minutes = int(ts.split(":")[0]) if ":" in ts else 0
        seconds = int(ts.split(":")[1]) if ":" in ts and len(ts.split(":")) > 1 else 0
        total_seconds = minutes * 60 + seconds

        if current_chapter is None:
            current_chapter = {"start": ts, "lines": [], "end": ts}
        elif total_seconds - _parse_ts(current_chapter["end"]) > 30:
            chapters.append(current_chapter)
            current_chapter = {"start": ts, "lines": [], "end": ts}

        current_chapter["lines"].append(text)
        current_chapter["end"] = ts

    if current_chapter:
        chapters.append(current_chapter)

    result = [f"# Chapters: {title}", ""]
    for i, ch in enumerate(chapters, 1):
        preview = ch["lines"][0][:80] if ch["lines"] else ""
        result.append(f"{ch['start']} Chapter {i} — {preview}")
    result.append("")
    result.append("---")
    result.append(f"*Generated by echo-core-content-agent*")

    return "\n".join(result)


def _parse_ts(ts: str) -> int:
    """Parse a MM:SS or HH:MM:SS timestamp to total seconds."""
    parts = ts.split(":")
    if len(parts) == 2:
        return int(parts[0]) * 60 + int(parts[1])
    elif len(parts) == 3:
        return int(parts[0]) * 3600 + int(parts[1]) * 60 + int(parts[2])
    return 0


def format_blog_post(transcript: str, title: str) -> str:
    """Format the transcript as a blog post."""
    lines = transcript.strip().split("\n")
    first_line = lines[0].split(" ", 1)[1] if " " in lines[0] else "Introduction"
    word_count = len(transcript.split())

    return f"""# {title}

> A deep dive into the content. Generated from video transcript.

## Introduction

{first_line}…

## Key Takeaways

The video covers content across {len(lines)} segments with approximately {word_count} words of spoken content.

## Full Content

{transcript}

## Conclusion

This content was processed by the Echo Core Content Agent, transforming video into written form for easy reference and sharing.

---
*Generated by echo-core-content-agent | {datetime.now(timezone.utc).isoformat()}*
"""


def format_thread(transcript: str, title: str) -> str:
    """Format as a Twitter/X thread."""
    lines = transcript.strip().split("\n")
    tweets = []
    buffer = ""

    for line in lines:
        text = line.split(" ", 1)[1] if " " in line else line
        # Clean up music/lyrics markers
        text = text.replace("♪", "").strip()
        if not text:
            continue
        if len(buffer) + len(text) + 3 > 280:
            tweets.append(buffer.strip())
            buffer = text
        else:
            buffer += " " + text if buffer else text

    if buffer:
        tweets.append(buffer.strip())

    result = [f"1/ 🧵 {title}"]
    for i, tweet in enumerate(tweets[:20], 2):  # Cap at 20 tweets
        result.append(f"{i}/ {tweet}")

    return "\n\n".join(result[:21])  # 1 intro + 20 content max


def format_quotes(transcript: str, title: str) -> str:
    """Extract notable quotes with timestamps."""
    lines = transcript.strip().split("\n")
    quotes = []
    for line in lines:
        if " " in line:
            ts = line.split(" ", 1)[0]
            text = line.split(" ", 1)[1].replace("♪", "").strip()
            if len(text) > 40 and text not in [q[1] for q in quotes]:
                quotes.append((ts, text))

    # Remove duplicates and limit
    seen = set()
    unique_quotes = []
    for ts, text in quotes:
        if text not in seen:
            seen.add(text)
            unique_quotes.append((ts, text))

    result = [f"# Quotes: {title}", ""]
    for ts, text in unique_quotes[:15]:
        result.append(f"> \"{text}\"")
        result.append(f"— {ts}")
        result.append("")

    result.append("---")
    result.append(f"*Generated by echo-core-content-agent*")

    return "\n".join(result)


def save_output(content: str, title: str, fmt: str) -> Path:
    """Save transformed content to the output directory."""
    CONTENT_DIR.mkdir(parents=True, exist_ok=True)
    slug = "".join(c if c.isalnum() or c in " -_" else "" for c in title).lower()
    slug = slug.replace(" ", "-")[:50]
    filename = f"{slug}-{fmt}.md"
    path = CONTENT_DIR / filename
    path.write_text(content)
    return path


def log_agent(action: str, video_id: str, fmt: str, tier: str, status: str, path: str):
    """Append to the shared agent log."""
    AGENT_LOG.parent.mkdir(parents=True, exist_ok=True)
    entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "agent": "content-agent",
        "action": action,
        "input": video_id,
        "format": fmt,
        "tier": tier,
        "status": status,
        "output_path": path,
    }
    with open(AGENT_LOG, "a") as f:
        f.write(json.dumps(entry) + "\n")


def main():
    parser = argparse.ArgumentParser(description="Content Agent — YouTube → structured content")
    parser.add_argument("url", help="YouTube URL or video ID")
    parser.add_argument("--format", "-f", choices=["summary", "chapters", "blog-post", "thread", "quotes"],
                        default="summary", help="Output format (default: summary)")
    parser.add_argument("--title", "-t", default=None, help="Video title (auto-detected if not provided)")
    args = parser.parse_args()

    print(f"Content Agent: Processing {args.url}")
    print(f"Format: {args.format}")

    # Step 1: Fetch transcript
    print("Fetching transcript...")
    try:
        transcript = fetch_transcript(args.url)
    except Exception as e:
        print(f"ERROR: {e}")
        log_agent("fetch_failed", args.url, args.format, "none", "failed", "")
        sys.exit(1)

    if not transcript:
        print("ERROR: Empty transcript received")
        log_agent("fetch_failed", args.url, args.format, "none", "empty", "")
        sys.exit(1)

    word_count = len(transcript.split())
    print(f"Transcript fetched: {word_count} words")

    # Step 2: Classify
    task_desc = f"Summarize YouTube video content ({word_count} words)"
    routing = classify_task(task_desc)
    print(f"Routing: {routing['tier']} → {routing['model']} (complexity: {routing['complexity']})")

    # Log routing decision
    log_routing(f"content-{args.url[-11:]}", task_desc, routing["tier"],
                routing["model"], routing["provider"], routing["complexity"])

    # Step 3: Transform
    title = args.title or f"YouTube Video ({args.url[-11:]})"

    formatters = {
        "summary": format_summary,
        "chapters": format_chapters,
        "blog-post": format_blog_post,
        "thread": format_thread,
        "quotes": format_quotes,
    }

    formatter = formatters.get(args.format, format_summary)
    content = formatter(transcript, title)

    # Step 4: Save
    output_path = save_output(content, title, args.format)
    print(f"Saved: {output_path}")

    # Step 5: Log
    log_agent("transform", args.url[-11:], args.format, routing["tier"], "completed", str(output_path))

    # Step 6: Report
    lines = transcript.strip().split("\n")
    print()
    print("=== CONTENT AGENT REPORT ===")
    print(f"Input: {title}")
    print(f"Format: {args.format}")
    print(f"Tier: {routing['tier']} ({routing['model']})")
    print(f"Complexity: {routing['complexity']}")
    print(f"Output: {output_path}")
    print(f"Duration: {lines[0].split()[0] if lines else 'unknown'} – {lines[-1].split()[0] if lines else 'unknown'}")
    print(f"Segments: {len(lines)}")
    print(f"Words: {word_count}")


if __name__ == "__main__":
    main()